### ISSUE TITLE
`npm run test` doesn't do anything

### ISSUE THREAD

**Issue by PoignardAzur** [mimani/vue-just-another-dropdown#1]
`npm run test` calls `npm run unit`, which doesn't exist.

Either the "scripts" section should be removed from package.json, or a `unit` script should be added.

**Comment by mimani** [comment]
I have removed this from the `scripts` section, as there are no unit tests at the moment. You can contribute to this repo if you want to. You can add unit test or more features. You can connect with me at mimani.saurabh@gmail.com if you want to discuss anything regarding this.

Thanks.
Saurabh
